import Navbar from './NavBar'
import Footer from './Footer'

import Head from 'next/head'
import Script from 'next/script'

export default function Layout({children}) {
  return (
    <>
    <Head>
        <link rel="shortcut icon" href="/images/favicon.ico"/>
        <title>Layout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />

    </Head>
    <Navbar/>
    <main>{children}</main>
    <Footer/>    
    <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"/>
    <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"/>
    </>
  )
}
